version: '3'

services:
  database:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=tasks
    volumes:
      - ./postgres:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
    command: node --trace-warnings -r dotenv/config dist/index.js
    environment:
      - DATABASE_URL=postgresql://admin:admin@database:5432/tasks
      - JWT_SECRET=yabbadabba
      - JWT_EXPIRES_IN=1d
    depends_on:
      - database

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - client
      - api
