apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: dswhitely1/todo_api
          ports:
            - containerPort: 3000
          env:
            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  key: jwtExpires
                  name: api-config-map
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwtSecret
                  name: api-secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: databaseUrl
                  name: api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config-map
data:
  jwtExpires: 1d
